import "./globals.css";
import Head from "next/head";
import ApolloWrapper from "./_app";
import { Open_Sans, Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  seo,
  children,
  title,
  desc,
  hasClass,
  classOpt,
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <div
          className={`main-wrapper ${
            hasClass ? "overflow-hidden" : "overflow-hidden"
          } ${classOpt}`}
        >
          <Head>
            {title && <title>{title}</title>}
            {desc && <meta name="description" content={desc} />}
            <link rel="icon" href="/fav_icon.png" />
          </Head>
          <ApolloWrapper>{children}</ApolloWrapper>
        </div>
      </body>
    </html>
  );
}
